### ISSUE TITLE
kvkens你好

### ISSUE THREAD

**Issue by LiuEcho** [kvkens/LearningNode#1]
kvkens你好，我是个新手。。学习你的LearningNode项目的代码，但是发现有个错误（或者别的？）
![qq 20151229161230](https://cloud.githubusercontent.com/assets/15226936/12031482/777bdfdc-ae47-11e5-9458-b4a24d30acf1.png)
![qq 20151229161240](https://cloud.githubusercontent.com/assets/15226936/12031484/7785d924-ae47-11e5-8be9-118d4c631cca.png)
![qq 20151229161447](https://cloud.githubusercontent.com/assets/15226936/12031483/7783be28-ae47-11e5-9929-662dccb7bd8e.png)
如图，这个我调试了一会，还是不知道什么情况，只好提个问题给你了。。你可以解决下吗？

**Comment by kvkens** [comment]
Hello,liu chang,首先很开心能下载我的代码，这个项目是去年学习node.js的时候，自己照着书本以及CNODEJS社区、慕课网 所学习搭建的。

不知道你的config文件是怎么配置的，由于是demo练手的，所以我没有做到智能分析URL域名的问题，需要手动配置，但是我看到你的截图，是属于jQuery语法错误，分隔符错误，不知道你用没有bower install 进行前端库依赖下载呢？

**Comment by LiuEcho** [comment]
前端库我肯定是下载了的，因为主页上的样式是好的，但是单个专辑页会有报错的问题，而它们是共用你的header.ejs的（只是他们的层级不一样？？）。。因为因为控制台上错误报在第一行，我也百度了一下Uncaught SyntaxError: Unexpected token <的错，解决方法也是众说纷纭。。

**Comment by kvkens** [comment]
你不能单独访问我的ejs模板，一个页面是由公共头+身体+公共尾巴组成的。
当然会错的啊！ ：）

**Comment by LiuEcho** [comment]
并没有单独访问啊，从主页上点击单个专辑进去的
